In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [3]:
x = data[['size', 'year']]
y = data['price']

In [4]:
lireg = LinearRegression()
reg = lireg.fit(x,y)

In [5]:
x.shape

(100, 2)

In [8]:
reg.score(x,y)

0.7764803683276796

In [9]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [10]:
reg.intercept_

-5772267.017463278

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [15]:
p_value = f_regression(x,y)[1].round(3)
p_value

array([0.   , 0.357])